version: '2'

services:
  php-cli:
    build: docker/php74-cli
    container_name: php74-cli
    working_dir: "/var/code/"
    volumes:
      - ./:/var/code:rw,cached
    networks:
      - app-network

  db:
    image: mysql:8.0.20
    container_name: mysql8
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: content
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql

    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge